module.exports = {
  messages:{
    "errorRetreivingData": "Error occurred while retrieving the data",
    "successRetreivingData": "Data retrieved successfully ",
    "successSendingForgotPasswordEmail": "Password sent successfully",
    "successSendingForgotPasswordLink": "Please check your e-mail to reset your password",
    "errorSendingForgotPasswordEmail": "Username does not exist in our database",
    "userSuccess": "User saved successfully",
    "userUpdateSuccess": "Updated successfully",
    "saveSuccessfully": "Successfully saved",
    "invalidEmailPassword": "Invalid email or password.",
    "requiredParams": "Please pass the required parameters",
    "mailSentSuccessfully": "E-mail sent successfully",
    "updatedSuccessfully": "Updated successfully",
    "adminForgotPassword": "We have emailed you a link to reset your password",
    "passwordResetToken": "Password reset token is invalid or has expired",
    "adminUserNotFoundInDatabase": "This user is not found in database",
    "emailAlreadyExist": "Your e-mail address is already associated with another account",
    "userCorporationSuccess": "Account created successfully.",
    "unableToProccessRequest":"Unable to proccess request",
    "unauthorizedRequest" : "Unauthorized request!!",
    "notFound": "Not found!!",
    "cidNotFound": "CID not found!!",
    "productSlugNotFound": "Product slug not found",
    "productNotFound": "Product not found",
    "requiredData": "Please pass the required data",
    "sessionIdNotFound": "Session id not found",
    "filledRequired": "Please fill out all fields.",
    "insertSamePassword": "Please insert the same password",
    "invalidEmail": "Please insert the valid email",
    "userNotFound": "User not found",
    "passwordChanged": "Success! Your password has been changed",
    "categoryIdNotFound": "Category Id not found",
    "userProfileNotUpdated":"User profile not updated",
    "userAddressNotUpdated": "User address not updated",
    "addressNotFound": "Address not found",
    "addressPramsNotFound": "Address prams not found",
    "tokenRequired":"Token required",
    "OldPasswordDoesNotMatch":"Old password doesn't match",
    "attributesNotFound":"Attributes not found",
    "CouponCodeNotFound":"CouponCodeNotFound",
    "WishlistEmpty":"Wishlist Empty",
    "ProductExistinWishlist":"Product Already Exist in Wishlist"
  }
}
